# Generated by Django 6.0.4 on 2026-05-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('receipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('receipe_name', models.CharField(max_length=100)),
                ('receipe_description', models.TextField()),
                ('receipe_image', models.ImageField(upload_to='receipe_images/')),
            ],
        ),
    ]
